"use client";

import { useMemo, useState } from "react";
import drafts from "./drafts.json";

type Row = Record<string, string | number | null>;
export type RosterData = { season:number; rosterSize:number; salaryCap:number; rules:Row[]; decisions:Row[]; teams:Array<{team:string;owner:string;summary:Row;committed:Row[];projected:Row[];expiring:Row[];prospects:Row[]}> };

const money = (value:unknown) => `$${Number(value ?? 0)}`;
const playerUrl = (name:unknown) => `https://www.baseball-reference.com/search/search.fcgi?search=${encodeURIComponent(String(name ?? ""))}`;

function Timeline({row}:{row:Row}) {
  const contract=String(row["2027 Contract"]??row.Contract??"");
  const salary=Number(row["2027 $"]??0);
  let years:Array<{year:number;salary:number}>=[];
  if(/^\d+$/.test(contract)) years=Array.from({length:Number(contract)},(_,i)=>({year:2027+i,salary}));
  else if(contract==="3mL") years=[{year:2027,salary:0},{year:2028,salary:5},{year:2029,salary:15}];
  else if(contract==="2mL") years=[{year:2027,salary:5},{year:2028,salary:15}];
  else if(contract==="1mL"||contract==="1FA") years=[{year:2027,salary}];
  return <div className="contract-timeline">{years.length?years.map(item=><span key={item.year}><small>{item.year}</small><b>{money(item.salary)}</b></span>):<em>No 2027 commitment</em>}</div>;
}

function PlayerTable({title,subtitle,rows,kind}:{title:string;subtitle:string;rows:Row[];kind:string}) {
  return <section className="roster-section"><div className="roster-section-head"><div><h3>{title}</h3><p>{subtitle}</p></div><span>{rows.length}</span></div>{rows.length?<div className="roster-player-list">{rows.map((row,index)=>{
    const name=String(row.Player??"");
    const draft=drafts.flatMap(d=>d.picks.map(p=>({...p,year:d.year}))).find(p=>p.player.toLowerCase()===name.toLowerCase());
    return <article className={`roster-player ${kind}`} key={`${name}-${index}`}><div className="player-identity"><a href={playerUrl(name)} target="_blank" rel="noreferrer">{name}</a><span>{row.Pos||"—"} · {row.MLB||row["MLB Org"]||"—"}</span>{draft&&<small>Drafted {draft.year} · #{draft.overall} overall</small>}</div><div className="player-status"><small>{row["2026 Status"]||row["2027 Projection"]||row.Type||"Status"}</small><b>{row["2027 Contract"]||row.Contract||"—"}</b></div><Timeline row={row}/><div className="player-points"><small>2026 FPTS</small><b>{Number(row["2026 FPTS"]??0).toLocaleString("en-US",{maximumFractionDigits:2})}</b></div>{(row.Basis||row.Comment)&&<p className="player-note">{row.Basis||row.Comment}</p>}</article>})}</div>:<p className="roster-empty">None currently projected.</p>}</section>;
}

function RosterDepthChart({rows}:{rows:Row[]}) {
  const slots=["C","1B","2B","3B","SS","OF","OF","OF","UTIL","UTIL","SP","SP","SP","SP","SP","RP","RP","RP","BN","BN","BN","BN"];
  const remaining=rows.map((row,index)=>({row,index}));
  const eligible=(row:Row,slot:string)=>{const pos=String(row.Pos??"").split(",").map(item=>item.trim());if(slot==="BN")return true;if(slot==="UTIL")return pos.some(item=>!["SP","RP","P"].includes(item));return pos.includes(slot)||(slot==="SP"&&pos.includes("P"))||(slot==="RP"&&pos.includes("P"));};
  const assigned=slots.map(slot=>{const match=remaining.findIndex(item=>eligible(item.row,slot));return {slot,player:match<0?null:remaining.splice(match,1)[0].row};});
  return <section className="depth-chart"><div className="depth-row heading"><span>Slot</span><span>Player</span><span>Pos</span><span>2027</span><span>Deal</span><span>2026 FPTS</span></div>{assigned.map(({slot,player},index)=><div className={`depth-row${player?"":" empty-slot"}`} key={`${slot}-${index}`}><b>{slot}</b>{player?<><a href={playerUrl(player.Player)} target="_blank" rel="noreferrer">{player.Player}</a><span>{player.Pos}</span><strong>{money(player["2027 $"])}</strong><span>{player["2027 Contract"]||player.Contract||"—"}</span><span>{Number(player["2026 FPTS"]??0).toLocaleString("en-US",{maximumFractionDigits:1})}</span></>:<><em>Empty</em><span>—</span><span>—</span><span>—</span><span>—</span></>}</div>)}</section>;
}

export function RosterPortal({data,onLock}:{data:RosterData;onLock:()=>void}) {
  const [selected,setSelected]=useState(data.teams[0].team);
  const [view,setView]=useState<"team"|"contracts"|"auction"|"farm"|"rules">("team");
  const [position,setPosition]=useState("All");
  const team=useMemo(()=>data.teams.find(item=>item.team===selected)??data.teams[0],[data,selected]);
  const summary=team.summary;
  const projectedLeft=Number(summary["Projected $ Left"]??0);
  const auction=useMemo(()=>data.teams.flatMap(item=>[...item.expiring.map(row=>({...row,FormerTeam:item.team,Owner:item.owner,AuctionStatus:"Expected Auction"})),...item.projected.filter(row=>String(row.Type)==="FA Option").map(row=>({...row,FormerTeam:item.team,Owner:item.owner,AuctionStatus:"Possible Keeper"}))]).filter(row=>position==="All"||String(row.Pos).split(",").includes(position)).sort((a,b)=>Number(b["2026 FPTS"]??0)-Number(a["2026 FPTS"]??0)),[data,position]);
  const farm=useMemo(()=>data.teams.flatMap(item=>item.prospects.map(row=>({...row,FantasyTeam:item.team,Owner:item.owner}))).filter(row=>position==="All"||String(row.Pos).split(",").includes(position)).sort((a,b)=>Number(a["MLB Pipeline Rank"]??999)-Number(b["MLB Pipeline Rank"]??999)||Number(String(b["Roster %"]??"0").replace("%",""))-Number(String(a["Roster %"]??"0").replace("%",""))),[data,position]);
  const positions=["All","C","1B","2B","3B","SS","OF","SP","RP"];
  const contractRows=[...team.committed,...team.projected];
  const teamDrafts=drafts.filter(draft=>draft.year===2026).flatMap(draft=>draft.picks.filter(pick=>pick.owner===team.owner).map(pick=>({...pick,year:draft.year,current:team.prospects.some(row=>String(row.Player).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()===pick.player.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase())}))).sort((a,b)=>a.overall-b.overall);
  const farmSystems=data.teams.map(item=>{const ranked=item.prospects.filter(row=>row["MLB Pipeline Rank"]);return {item,ranked:ranked.length,score:ranked.reduce((sum,row)=>sum+101-Number(row["MLB Pipeline Rank"]),0)};}).sort((a,b)=>b.score-a.score||b.ranked-a.ranked);
  const salaryYears=(row:Row)=>{const contract=String(row["2027 Contract"]??row.Contract??"");const salary=Number(row["2027 $"]??0);if(/^\d+$/.test(contract))return [2027,2028,2029].map((year,i)=>i<Number(contract)?salary:null);if(contract==="3mL")return [0,5,15];if(contract==="2mL")return [5,15,null];if(contract==="1mL"||contract==="1FA")return [salary,null,null];return [null,null,null];};
  return <section className="ledger roster-portal">
    <div className="roster-command"><div><span>2027 FRONT OFFICE</span><h2>Pre-Draft Roster Room</h2></div><div className="roster-command-actions"><div className="roster-view-tabs">{[["team","Roster"],["contracts","Budget"],["auction","Auction Pool"],["farm","Farm Rankings"],["rules","Rules"]].map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id as typeof view)}>{label}</button>)}</div><button className="lock-rosters" onClick={onLock}>Lock</button></div></div>
    {(view==="team"||view==="contracts")&&<div className="team-selector"><label>Club<select value={selected} onChange={e=>setSelected(e.target.value)}>{data.teams.map(item=><option key={item.team}>{item.team}</option>)}</select></label><div><span>{team.owner}</span><h2>{team.team}</h2></div></div>}
    {view==="rules"?<div className="roster-rules"><section><h3>Contract projection rules</h3>{data.rules.map((rule,i)=><article key={i}><strong>{rule.Rule}</strong><span>{rule["2027 Treatment"]}</span><p>{rule.Reason}</p></article>)}</section><section><h3>Current projection decisions</h3>{data.decisions.map((decision,i)=><article key={i}><strong>{decision.Player}</strong><span>{decision.Team} · {decision.Decision}</span><p>{decision.Basis}</p></article>)}</section></div>:view==="auction"?<><div className="board-head"><div><h2>2027 Auction Pool</h2><p>All expiring contracts · possible keepers remain listed</p></div><label>Position<select value={position} onChange={e=>setPosition(e.target.value)}>{positions.map(p=><option key={p}>{p}</option>)}</select></label></div><div className="data-board"><div className="data-row auction-row heading"><span>#</span><span>Player</span><span>Pos</span><span>Former team</span><span>Old salary</span><span>Status</span><span>2026 FPTS</span></div>{auction.map((row,i)=><div className="data-row auction-row" key={`${row.Player}-${row.FormerTeam}`}><b>{i+1}</b><a href={playerUrl(row.Player)} target="_blank" rel="noreferrer">{row.Player}</a><span>{row.Pos}</span><span>{row.FormerTeam}</span><strong>{money(row["2026 $"])}</strong><em className={row.AuctionStatus==="Possible Keeper"?"possible-keeper":""}>{row.AuctionStatus}</em><span>{Number(row["2026 FPTS"]??0).toLocaleString()}</span></div>)}</div></>:view==="farm"?<><div className="board-head"><div><h2>League Farm Rankings</h2><p>Current MLB Pipeline rank first, then roster rate · includes projected graduates</p></div><label>Position<select value={position} onChange={e=>setPosition(e.target.value)}>{positions.map(p=><option key={p}>{p}</option>)}</select></label></div><div className="farm-system-strip">{farmSystems.map(({item,ranked,score})=><button key={item.team} onClick={()=>{setSelected(item.team);setView("team")}}><strong>{item.team}</strong><span>{ranked} Top 100 · {score} pts</span></button>)}</div><div className="data-board"><div className="data-row farm-heading heading"><span>Rank</span><span>Player</span><span>Pos</span><span>Fantasy team</span><span>MLB Org</span><span>2027 outlook</span></div>{farm.map((row,i)=><div className="data-row farm-heading" key={`${row.Player}-${row.FantasyTeam}`}><b>{row["MLB Pipeline Rank"]?`#${row["MLB Pipeline Rank"]}`:`— ${i+1}`}</b><a href={playerUrl(row.Player)} target="_blank" rel="noreferrer">{row.Player}</a><span>{row.Pos}</span><span>{row.FantasyTeam}</span><span>{row["MLB Org"]}</span><strong>{row["2027 Projection"]}</strong></div>)}</div><p className="ranking-source">Current ranks: MLB Pipeline in-season Top 100, August 2026. Unranked players are ordered by roster percentage.</p></>:view==="contracts"?<>
      <div className="budget-dashboard"><article><small>Projected payroll</small><strong>{money(summary["Projected $"])}</strong><span>of {money(data.salaryCap)}</span></article><article className="budget-available"><small>Draft budget</small><strong>{money(projectedLeft)}</strong><span>{summary["Projected Spots Left"]} open spots</span></article><article><small>Buying power</small><strong>{money(summary["Projected $/Spot"])}</strong><span>per open spot</span></article><article><small>Committed core</small><strong>{summary["Committed Players"]}</strong><span>{money(summary["Committed $"])} locked in</span></article><div className="cap-meter"><i style={{width:`${Math.min(100,Number(summary["Projected $"]??0)/data.salaryCap*100)}%`}}/><span>{Math.round(Number(summary["Projected $"]??0)/data.salaryCap*100)}% of cap</span></div></div>
      <div className="contract-grid"><div className="contract-grid-row heading"><span>Player</span><span>Pos</span><b>2027</b><b>2028</b><b>2029</b></div>{contractRows.map((row,i)=><div className="contract-grid-row" key={`${row.Player}-${i}`}><a href={playerUrl(row.Player)} target="_blank" rel="noreferrer">{row.Player}</a><span>{row.Pos}</span>{salaryYears(row).map((salary,index)=><b key={index}>{salary===null?"—":money(salary)}</b>)}</div>)}</div>
    </>:<>
      <div className="budget-dashboard"><article><small>Projected payroll</small><strong>{money(summary["Projected $"])}</strong><span>of {money(data.salaryCap)}</span></article><article className="budget-available"><small>Draft budget</small><strong>{money(projectedLeft)}</strong><span>{summary["Projected Spots Left"]} open roster spots</span></article><article><small>Buying power</small><strong>{money(summary["Projected $/Spot"])}</strong><span>available per open spot</span></article><article><small>Committed core</small><strong>{summary["Committed Players"]}</strong><span>{money(summary["Committed $"])} locked in</span></article><div className="cap-meter"><i style={{width:`${Math.min(100,Number(summary["Projected $"]??0)/data.salaryCap*100)}%`}}/><span>{Math.round(Number(summary["Projected $"]??0)/data.salaryCap*100)}% of cap committed/projected</span></div></div>
      <div className="roster-section-head depth-title"><div><h3>Projected 22-Man Roster</h3><p>Eligible players placed into lineup, pitching and bench slots</p></div><span>{contractRows.length}</span></div>
      <RosterDepthChart rows={contractRows}/>
      <PlayerTable title="Farm System" subtitle="0mL prospects whose contract clock has not started" rows={team.prospects} kind="prospect"/>
      <section className="drafted-prospects"><div className="roster-section-head"><div><h3>2026 Minor League Draft</h3><p>Recorded selections for this owner</p></div><span>{teamDrafts.length}</span></div>{teamDrafts.map(pick=><div className="drafted-prospect" key={`${pick.year}-${pick.overall}`}><b>{pick.year}</b><span>#{pick.overall}</span><a href={playerUrl(pick.player)} target="_blank" rel="noreferrer">{pick.player}</a><em>{pick.current?"Current farm":"2026 selection"}</em></div>)}</section>
    </>}
  </section>;
}
